import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// import components
import Navbar from "../components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import ScreenSizeHelper from '@/components/ScreenSizeHelper';
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
        >
          <Navbar />
          <div className="w-full max-w-7xl mx-auto flex flex-col items-center">
            {children}
          </div>
          <ScreenSizeHelper />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
